- name: variables from the another vars file
  hosts: web
  vars_files:
    - vars.yaml # variables assigned here
  tasks:
    - name: variables will be assigned from a another file
      ansible.builtin.debug: # variables are from vars.yaml
        msg: "My name is {{Father_Name}} and my son name is {{Name}} his age is {{age}}"